parameters:
  additionalVars: ''
  varFile: ''
  backendArg: ''
  azureSubscription: ''
  rootFolder: ''
  artifactName: 'plan'
  pool: 
    vmImage: 'ubuntu-latest'
jobs:
- job: plan
  displayName: Terraform Plan
  pool: ${{ parameters.pool }}
  steps:
  - template: get-tf-credentials.steps.yml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
  - script: |
      terraform init -no-color -input=false ${{ parameters.backendArg }}
      terraform plan -no-color -input=false -var-file=${{ parameters.varFile }} ${{ parameters.additionalVars }} -out="$(Build.ArtifactStagingDirectory)/out.plan"
    workingDirectory: ${{ parameters.rootFolder }}
    displayName: Terraform Plan
  - task: PublishBuildArtifacts@1
    displayName: Publish Plan as an Artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: ${{ parameters.artifactName }}
      publishLocation: Container