trigger:
  - master

resources:
  repositories:
  - repository: templates
    type: github
    name: soccerjoshj07/pipeline-templates
    endpoint: soccerjoshj07

variables:
  devSubscription: demo-mslearn-tailspin-azure
  rootFolder: app

stages:
  - stage: plandev
    displayName: Plan DEV
    jobs:
    - template: terraform/terraform-plan-job.yml@templates
      parameters:
        varFile: 'terraform.DEV.tfvars'
        # additionalVars: '-var "agent_token=$(AgentPoolToken)" -var "psql_password=$(PSQLPassword-DEV)"'
        backendArg: '-backend-config=backend.DEV.tfvars'
        azureSubscription: ${{ variables.devSubscription }}
        rootFolder: $(rootFolder)
  - stage: applydev
    displayName: Apply DEV
    jobs:
    - template: terraform/terraform-apply-deployment.yml@templates
      parameters:
        environment: DEV
        backendArg: '-backend-config=backend.DEV.tfvars'
        azureSubscription: ${{ variables.devSubscription }}
        rootFolder: $(rootFolder)