name: terraform

on:
  push:
    branches:
    - main
  workflow_dispatch:
  pull_request: 
    branches:
    - main
    
jobs:
  terraform-plan:
    name: terraform plan
    uses: joshjohanning-org/reusable-workflows/.github/workflows/terraform-plan.yml@terraform
    with:
      runs-on: ubuntu-latest
      var-file: 'terraform.DEV.tfvars'
      backend-arg: '-backend-config=backend.DEV.tfvars'
      artifact-name: plan-dev
      working-directory: app
      environment: 'dev-plan'
