name: terraform

on:
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  terraform-plan:
    name: terraform plan
    uses: joshjohanning-workflows/workflow-terraform/.github/workflows/terraform-plan.yml@main
    with:
      runs-on: ubuntu-latest
      var-file: 'terraform.DEV.tfvars'
      backend-arg: '-backend-config=backend.DEV.tfvars'
      artifact-name: plan-dev
      working-directory: app
